### ISSUE TITLE
自删除不完全

### ISSUE THREAD

**Issue by Aquilao** [timwhitez/Doge-SelfDelete#1]
使用 bypass UAC 的管理员用户在 Windows 10 下测试  

运行程序自删除后还会留下一个大小为零的文件。  
这个文件无法删除，提示路径不存在，也无法创建同名文件，提示没有权限。  
在重启计算机后，此文件才会消失。  
感觉实际情况下还是会留下工具的文件名，有点不隐蔽。

想请教一下此工具是否是设计成这样的，还是我使用过程中有什么权限问题

![image](https://user-images.githubusercontent.com/25531497/144799065-e04bdc92-ad40-44fe-8953-999c1f873ecc.png)

**Comment by timwhitez** [comment]
我本机测试不存在这个问题，可能与内存操作的错误有关，暂时无法修复这个问题

**Comment by Aquilao** [comment]
“内存操作的错误”提醒了我，之前是被卡巴拦住了，关掉卡巴之后能正常运行，看来部分杀软可能会影响功能。谢谢师傅答疑解惑。

**Comment by timwhitez** [comment]
不是程序本身的错误就好，针对卡巴这种免杀就需要单独去想办法绕过了。
